# FROM almalinux:9.0
# RUN dnf install nginx -y
# RUN rm -rf /usr/share/nginx/html/index.html
# COPY index.html /usr/share/nginx/html/
# CMD ["nginx", "-g", "daemon off;"]

# FROM almalinux:9.0
# #CMD ["ping", "google.com"]
# ENTRYPOINT ["ping", "google.com"]

FROM almalinux:9.0
ENV course="DevSecOps"
ARG trainer="siva"
RUN echo "course:${course} and trainer:${trainer}"