networks:
  default:
    driver: bridge
    name: roboshop
    external: true #I created network already using docker network create roboshop

volumes:
  - mongodb
  - redis
  - mysql
  - rabbitmq

services:
  mongodb:
    image: saidoc11/mongodb:v1
    container_name: mongodb
    volumes:
      - mongodb:/data/db
  catalogue:
    image: saidoc11/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
      - redis:/data
  user:
    image: saidoc11/user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    image: saidoc11/cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis
  mysql:
    image: saidoc11/mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  shipping:
    image: saidoc11/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    - cart
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    volumes:
    - rabbitmq:var/lib/rabbitmq
  payment:
    image: saidoc11/payment:v1
    container_name: payment
    environment:
      CART_HOST: cart 
      CART_PORT: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
    depends_on:
    - rabbitmq
    - user
    - cart
  frontend:
    image: saidoc11/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment
