FROM node:alpine3.21
WORKDIR /opt/server
COPY *.json /opt/server
COPY package.json /opt/server
RUN npm install
ENV MONGO_URL="mongodb://mongo:27017/catalogue"
CMD ["node","server.js"]


FROM node:alpine3.21
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop
WORKDIR /opt/server
COPY package.json .
COPY *.js .
RUN npm install
RUN chown -R roboshop:roboshop /opt/server
ENV MONGO = "true" \
    MONGO_URL="mongodb://mongodb:27017/catalogue"
USER roboshop
CMD ["node","server.js"]